### ISSUE TITLE
Fix the types for the Button story in the `ui` project.

### ISSUE THREAD

**Issue by AdrianValdes** [small-ads/core#17]
Look into the types of the button component. As it is now all annotations for button are required ( you might want to read up on what is required type ), but we dont want all of them to be. 

We can fix this bit and then define the needed default propTypes. 
TIP: Default proptypes are useful in cases that a property isnt required.

**Comment by AdrianValdes** [comment]
Hello @paschalidi, Any input or advice on what should I read to solve this issue?

**Comment by paschalidi** [comment]
Hey want to read the description of the issue and see how you can go about it? 

Is the description helping? Basically you will need to figure out when a property is required for a component and when not. This is not a typescript specific situation it is in general a programing concept. You have required values for functions and others that are optional. We want however to express which props are optional and which not using typescript :) 


Hope this helps to begin with. Let me know

**Comment by AdrianValdes** [comment]
Oh, did that description was already there? I swear I checked and I didn't see it! My mistake, I will go into it. One question regarding this issue, we want to use **just**  Typescript, right? There is no point in using  `prop-types` on top of that as I understand so far.

**Comment by AdrianValdes** [comment]
I mean, I know I can make a prop like optional by putting a ? at the end, but I suppose we want to do it in a more robust way.

**Comment by paschalidi** [comment]
> There is no point in using prop-types on top of that as I understand so far.

That right, these two are solutions for the same problem

**Comment by paschalidi** [comment]
> I mean, I know I can make a prop like optional by putting a ? at the end of each property in the interface, but I suppose we want to do it in a more robust way.

Nope that's the right way to go about it :) Typescript is simple

**Comment by AdrianValdes** [comment]
Hi @paschalidi , I have two questions. 
1. I am getting an error that I don't know how to solve. I am trying to fix the issue like this. I don't know how to search for the solution to this problem.

```
type ButtonProps = {
  type?: 'primary' | 'secondary';
  id?: string;
  htmlType?: 'button' | 'submit' | 'reset' | undefined;
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
  disabled?: boolean | undefined;
  style?: object;
  className?: string;
  children: React.ReactNode;
} & typeof defaultProps;

const defaultProps = {
  id: null,
  onClick: () => {},
  type: 'primary',
  htmlType: 'button',
  style: {},
  disabled: false,
  className: '',
};

export function Button({
  type,
  id,
  htmlType,
  onClick,
  children,
  disabled,
  style,
  className,
}: ButtonProps) {
  return (
    <ButtonStyles>
      <button
        // eslint-disable-next-line react/button-has-type
        type={htmlType}
        id={id}
        disabled={disabled}
        onClick={onClick}
        className={`${className} ${type}`}
        style={style}
      >
        {children}
      </button>
    </ButtonStyles>
  );
}
Button.defaultProps = defaultProps;

```

But then, on then Buton.stories.tsx I am getting this error on the <Button><Button>: `This JSX tag's 'children' prop expects type 'never' which requires multiple children, but only a single child was provided.`
Or some like these one for other properties of the button `Type 'string' is not assignable to type 'never'`

**Comment by AdrianValdes** [comment]
2. The second question is about the way of asking questions. Am I doing it right? Or I am doing too soon. Should present you more information? Explain more my thinking process? Please, if you have any advice I would appreciate it. I would like to get better and ask questions in a correct way.

**Comment by AdrianValdes** [comment]
I think I find the source of the problem, is because I am not assigning any type to the `defaultProps` so it get type `never`. I could solve it saying:
```
const defaultProps: any = {
  id: null,
  onClick: () => {},
  type: 'primary',
  htmlType: 'button',
  style: {},
  disabled: false,
  className: '',
};

```
But we said and I know one should 99.99% of the times avoid the type `any`. I will try to find a very type to annotate it.

**Comment by paschalidi** [comment]
yeah I dont know about this resource. Might be good dont get me wrong. However what I would do would be between these lines. 

```
import React from "react";
import { ButtonStyles } from "./button.style";

export interface ButtonProps {
  type?: "primary" | "secondary";
  submit?: boolean;
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
  disabled?: boolean;
  style?: object;
  className?: string;
  children: React.ReactNode;
}

export function Button({
  type = "primary",
  submit = false,
  disabled = false,
  style = {},
  className = "",
  children,
  onClick = () => {},
}: ButtonProps) {
  return (
    <ButtonStyles>
      <button
        type={submit ? "submit" : "button"}
        disabled={disabled}
        onClick={onClick}
        className={`${className} ${type}`}
        style={style}
      >
        {children}
      </button>
    </ButtonStyles>
  );
}
```

Now I give you the solution but wont do that again. Lets consider this a lesson though :)

**Comment by AdrianValdes** [comment]
Shit I actually thought about using the JS default function parameters , that was the way I knew already! 

But I thought that would be not being declarative enough and not being "Typescripty"

**Comment by paschalidi** [comment]
hm I would do more research myself but I cant think of a reason why this isnt a good idea. Perhaps after few months somethings comes up I cant think about right now. But perhaps we can do some research on whats the best approach and why this might the one I am suggesting is having some drawbacks

**Comment by paschalidi** [comment]
Can you look into it?

**Comment by AdrianValdes** [comment]
The solution you gave me was actually the solution I first thought. It has the two features I knew already :), but then I started looking and looking and I didn't find a single example that would use it, that is what I dropped that idea, I even forgot about it. I stopped considering it somehow :(

**Comment by AdrianValdes** [comment]
If we put onClick like required we have to put an `onClick={() => {}}` method on every Button we created in the `Button.stories.tsx`. I suppose that is accepted.

**Comment by paschalidi** [comment]
Yep that is alright.

**Comment by AdrianValdes** [comment]
For now just more Buttons stories, am I wrong?

**Comment by paschalidi** [comment]
Yes right
