### ISSUE TITLE
create a repo for the ui library

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#2]
ac: 
* you install storybook
* you can run storybook 
* you can visit storybook on the browser
* you can see at least one story

**Comment by AdrianValdes** [comment]
Hello,
I have been learning a little bit about `Storybook` and how to set up a project that involves it together with `React` and `Typescript`. It is confusing sometimes, because the official documentation in Storybook is a bit outdated, but I think I found a solution.
 I have one more question for now is, in order to accomplish the last point of the ac ("you can see at least one story"), would you like me to do it with styled-components integrated at this point, or should I do it first with plain css.

**Comment by paschalidi** [comment]
Good question. I leave it up to you. We will end up using styled components if you wanna split the work in two issues and not do it together then feel free.

**Comment by AdrianValdes** [comment]
Ok. I will do separately. 

One more think, just to be 100% sure. We are going to install `storybook` direct in the root of our project, right? So .storybook would be in the root, and we would have `src/stories`

**Comment by AdrianValdes** [comment]
I suppose we could then move our stories later, but my main question is if I should install `storybook` directly in the root.

**Comment by paschalidi** [comment]
nope you will install it inside the `package/<name-of-the-ui-lib>`.

**Comment by paschalidi** [comment]
In the root you want to install only npm packages that are shared between all your projects.

**Comment by AdrianValdes** [comment]
Right, in this case, because we are using `lerna`, the root of the project is only for shared packages. 

> nope you will install it inside the `package/<name-of-the-ui-lib>`.
 Did you mean `packages/<...>`? So in the packages folder we create yesterday?

**Comment by paschalidi** [comment]
> Did you mean packages/<...>? So in the packages folder we create yesterday?

yes sorry my bad

**Comment by AdrianValdes** [comment]
And conventionally one uses the same name ==> `fe-small-advertisements` ?

**Comment by AdrianValdes** [comment]
My bad, I think you meant the actual name of the UI-library, so `storybook`

**Comment by paschalidi** [comment]
Right, you want to choose a descriptive name for the ui library.

**Comment by AdrianValdes** [comment]
I haven't find a way to install Storybook in a folder that it is outside the react project and make it work. I have been looking through your repos and cannot find any that has a similar structure, any advice on where to look?

Note: In another project that I created to practice I was able to add Storybook to React and use it, but just because I installed it directly in the React folder. I suppose that I have to fix something in the paths I cannot find. I will keep looking though.

**Comment by paschalidi** [comment]
m let me check

**Comment by paschalidi** [comment]
Did you try to create a cra project in the packages folder and then inside that cra project run `npx sb init`?

Try this I am sure this would work ;)

**Comment by AdrianValdes** [comment]
OH, I didn't know I should create another create-react-app project inside the packages folder. So inside core we are going to have **two cra** projects created? One for the app in /src/fe-small-advertisements and another one for the ui-library in packages/storybook

**Comment by paschalidi** [comment]
Check this documentation out
https://storybook.js.org/docs/react/get-started/install

**Comment by AdrianValdes** [comment]
I did, that is why at the beginning I though I should install storybook inside our fe-small-advertisements folder.

**Comment by AdrianValdes** [comment]
I think what I don't understand is the process of creating a the storybook project in another folder to then use it in our fe-small-advertisements app.

**Comment by AdrianValdes** [comment]
I thought we would use it directly inside of our fe-small-advertisements.

**Comment by paschalidi** [comment]
Nope. we want to have the ui components library and the `fe-small-advertisements` as separate projects. This way in the future if our organisation wants to reuse the `ui` library we are building for some other project they could basically install it as a package.

**Comment by AdrianValdes** [comment]
Shit, I got it now. I am going to set it up. I have to then learn how to link the two projects together.

**Comment by paschalidi** [comment]
I updated my comment above. I think this would make it clear for us. Connecting the together isnt such a painful job, I promise

**Comment by AdrianValdes** [comment]
I see, I see now.

**Comment by AdrianValdes** [comment]
My mind was trying to find another solution. One more thing for now, should I create the cra project for the ui-library using Typescript as well?

**Comment by AdrianValdes** [comment]
Or are in this case are we going to work wit js? I am not sure if it matters when we are going to connect them

**Comment by paschalidi** [comment]
Doesnt matter when we connect them, that's up to you. I would say we can use typescript to keep it consistent but this is up to you to decide, really. Feel free to use js and prop-types if you like it better

**Comment by AdrianValdes** [comment]
Got it, I will think about it. Thanks for the fast responses and the support! And my bad for missing small pieces, it is incredible how one small detail that one doesn't understand can cause so much confusion.

**Comment by paschalidi** [comment]
No worries keep it up
