### ISSUE TITLE
Configure react redux on the `fe`.

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#20]
Basically we want react to work with redux. And have a simple showcase that this is the case. 

For instance, clicking a button triggers an action. Some hardcoded value (string) is stored on the redux store and we display thin on the screen

**Comment by AdrianValdes** [comment]
Perfect. I am going to study a bit before setting up this. I haven't had time to finish the Typescript course, and I want the check how to integrate React, Redux and Typescript correctly.

**Comment by paschalidi** [comment]
You can also start this on Monday. :) No stress

**Comment by AdrianValdes** [comment]
One question, have you used or read about Redux-Toolkit? Just wondering, I haven't used. It is made by the Redux [team](https://redux-toolkit.js.org/).

**Comment by paschalidi** [comment]
use it!
