### ISSUE TITLE
user can login

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#40]
Acceptance criteria:
- [x]  There is a menu on the top of the screen where you can click Login. 
- [x] When you click login you are navigated to another route. There you see all the login options we provide - facebook, google, maybe more. Example of flow https://vercel.com/
- [x] When the user is logged in then they can click a button and logout. Session is cleared and the user could login again.
- [x] When user logs in they see the home page route where there is default list of ads

**Comment by AdrianValdes** [comment]
hi @paschalidi ,
Do you think it makes sense to build the `navbar` as a component in Storybook in a project like this? I think it may no be necessary but I am not sure.

**Comment by paschalidi** [comment]
You can decide. That I think as you say is on the edge. It doesnt have to be though in the components since it is not a reusable component. 

Very much depends on the agreement we wanna make on this. So as I said, you can choose what is better
