### ISSUE TITLE
create one reactjs project that uses typescript

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#5]
ac: 
* you use typescript
* you can see the hello world on the browser

**Comment by AdrianValdes** [comment]
Hi, 
in order to do this task we agreed to use create-react-app inside the src folder. Should I called the folder small-advertisements or server? Should be `core/src/server/` or `core/src/small-advertisements/`?

**Comment by paschalidi** [comment]
hey, something like `core/src/small-advertisements/` would be good. perhaps we want to capture also that this is a frontend app. Perhaps something like `core/src/fe-small-advertisements/` or something that you come up with that captures the fact that this application is a fe one. Imagine in the future you might wanna have in this folder also some backed apps..
