### ISSUE TITLE
Each story has all sizes

### ISSUE THREAD

**Issue by AdrianValdes** [small-ads/core#57]

**Comment by AdrianValdes** [comment]
hi @paschalidi,
What do you think, you we have the sizes for each button like this:

![image](https://user-images.githubusercontent.com/58083933/110235015-1572cb80-7f2e-11eb-8273-9f6bd7179692.png)
![image](https://user-images.githubusercontent.com/58083933/110235121-bd889480-7f2e-11eb-8771-fc5345f58ebf.png)


or like this:

![image](https://user-images.githubusercontent.com/58083933/110235110-aa75c480-7f2e-11eb-84e2-7d941803b2c1.png)

**Comment by AdrianValdes** [comment]
Also, is this something I should ask before making the PR like I did now? Or I should simply choose one and you can tell me to change it afterwards? Which way do think is better? How can I make your life easier?

**Comment by paschalidi** [comment]
I think both are fine but what you did is the best, first discuss then implement ;)
