### ISSUE TITLE
add eslint and prettier

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#6]
ac: 
* extract the eslint rules in its own package. The name needs to begin with the `eslint-config-` prefix. `eslint` requires that. 
Good example for what we wanna be doing is [this one](https://github.com/chakra-ui/chakra-ui/blob/develop/.eslintrc) from chackra. Yet understand that we dont want to override _all_ the rules they do, but only the ones that are making sense for us. This is most likely gonna be two or three rules since we just starting off. 
Another difference is that we want to export a js file and not a json as they do. If you look how others export their rules you will soon find out what I mean with exporting as `js`.

```
.
├── ...
├── packages                    
│   ├── ui                             # we have the ui library
│   ├── eslint-config-<our-name>       # we have the eslint rules we want to reuse in these two projects.
│   .
│   .
└── ...
```
* when the above is done you want to be able to run the eslint command using something like `npm run lint` from both the `ui` and the `fe-small-advertisments` projects. To do so isnt something very difficult, I could help but I want to let you do some research first on how this can be done.
* we want to have prettier also configured.

**Comment by paschalidi** [comment]
Hey, I wanted to update this issue a little bit. 

For the eslint rules it makes sense to create another package which will be living in the `packages` folder. Then we can reuse the configuration from that package in both the frontend app and the ui components. 

So I will update the requirements a little bit to make that more clear

**Comment by AdrianValdes** [comment]
OK, sounds good, I will wait for the requirements update.

**Comment by AdrianValdes** [comment]
I also saw in the AC that we are going to integrate Github actions in this
issue, so I am going to read more about it.

**Comment by paschalidi** [comment]
Okay acceptance criteria  is done now. I removed the last one which was about the `github` actions. We can tackle that on its own after this is finished

**Comment by AdrianValdes** [comment]
Hello @paschalidi, 
I have some doubts in how to accomplish those steps, but I want to keep doing research and try before asking for your help. Before doing that I have one question, in order to share our `config` our we going to publish them in npm? I think that maybe it is not necessary, but I believe you mentioned it at some point.

**Comment by AdrianValdes** [comment]
To be more clear, I don't know if you want me to solve all the AC steps locally, or if I should try to publish our shareable config in npm and then link the projects. I have been reading about it and it seems like it is possible both ways

**Comment by AdrianValdes** [comment]
Also should I follow any ideas to find a name for `eslint-config-<our-name>`? 
I just can come up with names like 
1. `eslint-config-small-advertisements`. (But I think that is not general enough)
2. `eslint-config-small-ads`(Also not general enough maybe)
3. `eslint-config-small-paschalidiAdrian` (...)

**Comment by paschalidi** [comment]
I think 1. or 2. would do the job.

**Comment by AdrianValdes** [comment]
Ok, good then.

**Comment by paschalidi** [comment]
> To be more clear, I don't know if you want me to solve all the AC steps locally, or if I should try to publish our shareable config in npm and then link the projects. I have been reading about it and it seems like it is possible both ways

You dont need to publish yet, because of lerna and the monorepos we dont really have to publish in npm. We could tho to practise this aspect as well. I remember me saying that we have to publish it. I must have been talking for something else or I might have been confused at the time

**Comment by AdrianValdes** [comment]
I see, I will try to find a solution for this case then.

**Comment by paschalidi** [comment]
This might sound complex but in the end will be pretty simple work ;) I promise

**Comment by AdrianValdes** [comment]
I believe you :). I had to make food and stuff but now I am doing research again, sometimes it is still confusing, but I think I am closer to make sense of all of it. 
For now I created a new folder `eslint-config-small-ads`, and I am trying to configure the `.eslintrc.js` from `fe-small-advertisements`. This is the structure I have:

├── ...
├── packages                    
│   ├── ui                           
│   ├── eslint-config-small-ads    
├── src
│   ├── fe-small-advertisements
│         ├── .eslintrc.js
└── ...

The .eslintrc.js from `fe-small-advertisements` is:

`module.exports = {
  extends: ["eslint-config-small-ads"],
};
`

Then, on the `package.json` inside `fe-small-advertisements` I added:

`"devDependencies": {
    "eslint": "^7.18.0",
    "eslint-config-small-ads": "file:../../packages/eslint-config-small-ads"
  }`
  
  and to the scripts
  
  `"scripts": {
     {...}
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },`

**Comment by AdrianValdes** [comment]
Nevertheless, I don't think that is the best option, as I have to re-install node-modules that are already in the project. I suppose I have to install dependencies on the `package.json` that is on the root of our project, at the same level as our `lerna.json`

**Comment by paschalidi** [comment]
You almost there. If you open a PR I can see what you mean better. Do your research and do it with your own pace tho.
