### ISSUE TITLE
google button design

### ISSUE THREAD

**Issue by AdrianValdes** [small-ads/core#65]

**Comment by AdrianValdes** [comment]
hi  @paschalidi,

My lack of designing expertise is hitting hard for this issue. I have search to find nice looking google buttons but all the most known sites I found use this button: 

![image](https://user-images.githubusercontent.com/58083933/110608920-ff167b00-818c-11eb-87e8-5814b0be71d0.png)


This is what I have so far:

![image](https://user-images.githubusercontent.com/58083933/110608602-b1017780-818c-11eb-8fb7-fa86e13ffdd9.png)

Any ideas or advice?

**Comment by AdrianValdes** [comment]
![image](https://user-images.githubusercontent.com/58083933/110615401-ad252380-8193-11eb-8f8c-fcbbf31bcae5.png)

**Comment by paschalidi** [comment]
Now is about right!

**Comment by AdrianValdes** [comment]
I was on it :D

**Comment by AdrianValdes** [comment]
I first put the google.svg in an images folder inside public `/public/images` but the linter complains when I import it because it is outside the `src` folder

**Comment by AdrianValdes** [comment]
I used `./src/components/svgs/`
